apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: openshift-logging
spec:
  data:
  - secretKey: access_key_id
    remoteRef:
      key: dev-openshift-logging-s3-credentials
      property: access_key_id
  - secretKey: secret_access_key
    remoteRef:
      key: dev-openshift-logging-s3-credentials
      property: access_key_secret
  - secretKey: bucketnames
    remoteRef:
      key: dev-openshift-logging-s3-credentials
      property: bucketnames
  - secretKey: region
    remoteRef:
      key: dev-openshift-logging-s3-credentials
      property: region
