apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logging-loki-aws
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: logging-loki-aws
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        access_key_id: "{{ .access_key_id }}"
        access_key_secret: "{{ .access_key_secret }}"
        bucketnames: "{{ .bucketnames }}"
        endpoint: "https://s3.{{ .region }}.amazonaws.com"
        region: "{{ .region }}"
        forcepathstyle: "false"
  data:
  - secretKey: access_key_id
    remoteRef:
      key: openshift-logging-s3-credentials
      property: access_key_id
  - secretKey: access_key_secret
    remoteRef:
      key: openshift-logging-s3-credentials
      property: access_key_secret
  - secretKey: bucketnames
    remoteRef:
      key: openshift-logging-s3-credentials
      property: bucketnames
  - secretKey: endpoint
    remoteRef:
      key: openshift-logging-s3-credentials
      property: endpoint
  - secretKey: region
    remoteRef:
      key: openshift-logging-s3-credentials
      property: region
  - secretKey: forcepathstyle
    remoteRef:
      key: openshift-logging-s3-credentials
      property: forcepathstyle
