apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccount:
    name: logcollector
  outputs:
   - name: loki-app
     type: loki
     loki:
       url: https://logging-loki-gateway-http.openshift-logging.svc:8080/api/logs/v1/application
       authentication:
         token:
           from: secret
           secret:
             name: lokistack-gateway-bearer-token
             key: token
     tls:
       ca:
         key: ca-bundle.crt
         secretName: lokistack-gateway-bearer-token
       insecureSkipVerify: false  # Production should use proper TLS validation
   - name: loki-infra
     type: loki
     loki:
       url: https://logging-loki-gateway-http.openshift-logging.svc:8080/api/logs/v1/infrastructure
       authentication:
         token:
           from: secret
           secret:
             name: lokistack-gateway-bearer-token
             key: token
     tls:
       ca:
         key: ca-bundle.crt
         secretName: lokistack-gateway-bearer-token
       insecureSkipVerify: false  # Production should use proper TLS validation
   # Production-specific: Separate audit output for compliance
   - name: loki-audit-compliance
     type: loki
     loki:
       url: https://logging-loki-gateway-http.openshift-logging.svc:8080/api/logs/v1/audit
       authentication:
         token:
           from: secret
           secret:
             name: lokistack-gateway-bearer-token
             key: token
     tls:
       ca:
         key: ca-bundle.crt
         secretName: lokistack-gateway-bearer-token
       insecureSkipVerify: false  # Production should use proper TLS validation
  pipelines:
   - name: send-app-logs
     inputRefs:
     - application
     outputRefs:
     - loki-app
   - name: send-infra-logs
     inputRefs:
     - infrastructure
     outputRefs:
     - loki-infra
   # Production-specific: Separate audit pipeline for compliance
   - name: send-audit-logs-compliance
     inputRefs:
     - audit
     outputRefs:
     - loki-audit-compliance
