---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-lokistack-bearer-token
  namespace: openshift-logging
spec:
  template:
    spec:
      serviceAccountName: logcollector
      containers:
      - name: create-secret
        image: registry.redhat.io/ubi8/ubi-minimal:latest
        command:
        - /bin/bash
        - -c
        - |
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/
          
          # Get token from logcollector-token secret
          TOKEN=$(kubectl get secret logcollector-token -n openshift-logging -o jsonpath='{.data.token}' | base64 -d)
          
          # Get CA certificate from configmap
          CA_CERT=$(kubectl get configmap openshift-service-ca.crt -n openshift-logging -o jsonpath='{.data.service-ca\.crt}')
          
          # Create or update the secret
          kubectl create secret generic lokistack-gateway-bearer-token \
            --from-literal=token="$TOKEN" \
            --from-literal=ca-bundle.crt="$CA_CERT" \
            --namespace=openshift-logging \
            --dry-run=client -o yaml | kubectl apply -f -
          
          echo "Secret lokistack-gateway-bearer-token created/updated successfully"
      restartPolicy: OnFailure
  backoffLimit: 3
