apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lokistack-bearer-token
  namespace: openshift-logging
spec:
  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore
  target:
    name: lokistack-gateway-bearer-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
        ca-bundle.crt: "{{ .ca_bundle }}"
  data:
  - secretKey: token
    remoteRef:
      key: logging-loki-gateway-token
      property: token
  - secretKey: ca_bundle
    remoteRef:
      key: openshift-service-ca.crt
      property: service-ca.crt
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: openshift-logging
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-sa
