apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
# Note: ClusterLogging CRD not available in OpenShift Logging 6.3
# Note: Log collection is automatically started when ClusterLogForwarder is created
# Note: namespace managed by logging-operator
# Note: cluster-log-forwarder managed by application-level overlays

commonLabels:
  app.kubernetes.io/name: cluster-logging
  app.kubernetes.io/component: log-collection
  app.kubernetes.io/part-of: openshift-logging
