apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/logging

labels:
- pairs:
    environment: dev
    component: logging-instance
  includeSelectors: true

patchesStrategicMerge:
- cluster-log-forwarder-dev.yaml

configMapGenerator:
- name: logging-config
  literals:
  - environment=dev
  - log_level=debug
  - retention_days=7
