apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-external-secrets-instance
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/tosin2013/openshift-logging-gitops.git
    targetRevision: HEAD
    path: base/external-secrets-operator/instance/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
