apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-forwarder-dev
  namespace: openshift-gitops
  labels:
    environment: dev
    component: logging-forwarder
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/tosin2013/openshift-logging-gitops.git
    targetRevision: HEAD
    path: overlays/dev/logging-forwarder
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
      - CreateNamespace=false
